tunnel: REPLACE_WITH_TUNNEL_UUID
credentials-file: /home/REPLACE_WITH_USER/.cloudflared/REPLACE_WITH_TUNNEL_UUID.json

ingress:
  - hostname: ipfs-api.nftfactory.org
    service: http://127.0.0.1:5002
  - hostname: ipfs.nftfactory.org
    service: http://127.0.0.1:8080
  - service: http_status:404
